# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu15.04"
  config.ssh.insert_key = false
  config.vm.define "kafka_base" do |server|
    server.vm.network "private_network", ip: "192.168.33.11"
    server.vm.provider :virtualbox do |vb|
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  config.vm.define "kafka_connector" do |server|
    server.vm.network "private_network", ip: "192.168.33.12"
  end
end
