- name: schema registry systemd script
  template:
    src: schema-registry.service.j2
    dest: /etc/systemd/system/schema-registry.service
    owner: root
    group: root
    mode: 644
    notify: start schema-registry
