- name: kafka connect distributed config
  template:
    src: distributed.properties.j2
    dest: /etc/kafka/distributed.properties
    owner: root
    group: root
    mode: 0644
  notify: start kafka-connect

- name: kafka connect start script
  template:
    src: kafka_connect_start.j2
    dest: /usr/bin/kafka_connect_start
    owner: root
    group: root
    mode: 0755
  notify: start kafka-connect

- name: kafka connect stop script
  template:
    src: kafka_connect_stop.j2
    dest: /usr/bin/kafka_connect_stop
    owner: root
    group: root
    mode: 0755
  notify: start kafka-connect

- name: kafka connect systemd script
  template:
    src: kafka-connect.service.j2
    dest: /etc/systemd/system/kafka-connect.service
    owner: root
    group: root
    mode: 644
  notify: start kafka-connect

- name: create connect-configs topic
  shell: kafka-topics --create --zookeeper kafka-base:2181 --topic connect-configs --replication-factor 1 --partitions 1 --config cleanup.policy=compact
  register: command_result
  failed_when: "'TopicExistsException' not in command_result.stderr"

- name: create connect-offsets topic
  shell: kafka-topics --create --zookeeper kafka-base:2181 --topic connect-offsets --replication-factor 1 --partitions 50 --config cleanup.policy=compact
  register: command_result
  failed_when: "'TopicExistsException' not in command_result.stderr"

- name: create connect-status topic
  shell: kafka-topics --create --zookeeper kafka-base:2181 --topic connect-status --replication-factor 1 --partitions 10 --config cleanup.policy=compact
  register: command_result
  failed_when: "'TopicExistsException' not in command_result.stderr"
